"""
def logs(settings='config.ini'):
    with open(settings, 'r') as f:
        config = []
        read = f.read()
        for item in read.splitlines():
            config.append(item.split('='))
    logging.basicConfig(filename=config[1][1],
                        level=config[3][1],
                        format=config[0][1],
                        datefmt=config[2][1])
    logger = logging.getLogger(__name__)
    return logger

log = logs()
"""

import logging
import os


def new_project():
    folder_name = input('What is the name of the new project?\n')
    assert isinstance(folder_name, str)
    os.mkdir(folder_name)
    os.mkdir(folder_name + '/media')
    folder_name += '/'
    index = folder_name + 'index.html'
    with open(index, 'w') as f:
        f.write('<!DOCTYPE HTML>\n')
        f.write('<html>\n')
        f.write('\t<head>\n')
        f.write('\t\t<title>\n')
        f.write('\t\t\tWebsite Title\n')
        f.write('\t\t</title>\n')
        f.write('\t\t<meta charset="utf-8">\n')
        f.write('\t\t<meta name="viewport" content="width=device-width, initial-scale=1">\n')
        f.write('\t\t<meta http-equiv="X-UA-Compatible" content="IE=edge" />\n')
        f.write('\t\t<link rel="stylesheet" type="text/css" href="./style.css">\n')
        f.write('\t\t<meta name="Description" content="">\n')
        f.write('\t\t<meta name="Keywords" content="">\n')
        f.write('\t\t<link rel="icon" type="image/x-icon" href="./favicon.ico">\n')
        f.write('\t\t<link rel="mask-icon" href="./favicon.svg" color="#990000">\n')
        f.write('\t\t<link rel="apple-touch-icon image_src" href="apple-touch-icon.png">\n')
        f.write('\t\t<link rel="manifest" href="manifest.webmanifest">\n')
        f.write('\t\t<script src="main.js"></script>\n')
        f.write('\t\t<!--[if lt IE 9]>\n')
        f.write('\t\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js">\n')
        f.write('\t\t\t</script>\n')
        f.write('\t\t<![endif]-->\n')
        f.write('\t</head>\n')
        f.write('\t<body>\n')
        f.write('\t\t<header>\n')
        f.write('\t\t</header>\n')
        f.write('\t\t<div>\n')
        f.write('\t\t\t<div id="main"\n')
        f.write('\t\t\t\t<p>Text here.</p>\n')
        f.write('\t\t\t</div>\n')
        f.write('\t\t\t<a href="#main" target="_self">\n')
        f.write('\t\t\t<img src="https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg" title="HTML5 logo" alt="Image not found" height="128px">\n')
        f.write('\t\t\t</a>\n')
        f.write('\t\t\t<noscript><strong>Please enable JavaScript to view this website properly.</strong></noscript>\n')
        f.write('\t\t</div>\n')
        f.write('\t\t<footer>\n')
        f.write('\t\t</footer>\n')
        f.write('\t</body>\n')
        f.write('</html>\n')
    with open(folder_name + 'style.scss', 'w') as f:
        f.write('$courier: "Courier New", courier, monospace;\n')
        f.write('\n')
        f.write('body {\n')
        f.write('\tfont-family: $courier;\n')
        f.write('}')
    with open(folder_name + 'manifest.webmanifest', 'w') as f:
        f.write('{\n')
        f.write('\t"short_name": "Example",\n')
        f.write('\t"name": "Example PWA",\n')
        f.write('\t"icons": [\n')
        f.write('\t\t{\n')
        f.write('\t\t\t"src": "media/icons-192.png",\n')
        f.write('\t\t\t"type": "image/png",\n')
        f.write('\t\t\t"sizes": "192x192"\n')
        f.write('\t\t},\n')
        f.write('\t\t{\n')
        f.write('\t\t\t"src": "media/icons-512.png",\n')
        f.write('\t\t\t"type": "image/png",\n')
        f.write('\t\t\t"sizes": "512x512"\n')
        f.write('\t\t}\n')
        f.write('\t],\n')
        f.write('\t"start_url": "/?source=pwa",\n')
        f.write('\t"background_color": "#FFFFFF",\n')
        f.write('\t"display": "standalone",\n')
        f.write('\t"theme_color": "#4285f4"\n')
        f.write('}\n')
        f.write('\n')
        f.write('\n')
        f.write('\n')
        f.write('\n')
        f.write('\n')
    with open(folder_name + 'browserconfig.xml', 'w') as f:
        f.write('<!--\n')
        f.write('Keep me in the root directory\n')
        f.write('-->\n')
        f.write('\n<?xml version="1.0" encoding="utf-8"?>\n')
        f.write('<browserconfig>\n')
        f.write('\t<msapplication>\n')
        f.write('\t\t<tile>\n')
        f.write('\t\t\t<square70x70logo src="media/mstile-70x70.png"/>\n')
        f.write('\t\t\t<square150x150logo src="media/mstile-150x150.png"/>\n')
        f.write('\t\t\t<wide310x150logo src="media/mstile-310x150.png"/>\n')
        f.write('\t\t\t<square310x310logo src="media/mstile-310x310.png"/>\n')
        f.write('\t\t\t<TileColor>#4285f4</TileColor>\n')
        f.write('\t\t</tile>\n')
        f.write('\t\t<badge>\n')
        f.write('\t\t\t<polling-uri src="badge.xml"/>\n')
        f.write('\t\t\t<frequency>30</frequency>\n')
        f.write('\t\t</badge>\n')
        f.write('\t\t<notification>\n')
        f.write('\t\t\t<polling-uri  src="1.xml"/>\n')
        f.write('\t\t\t<polling-uri2 src="2.xml"/>\n')
        f.write('\t\t\t<frequency>30</frequency>\n')
        f.write('\t\t\t<cycle>1</cycle>\n')
        f.write('\t\t</notification>\n')
        f.write('\t</msapplication>\n')
        f.write('</browserconfig>\n')
    with open(folder_name + 'sitemap.xml', 'w') as f:
        f.write('<!--\n')
        f.write('Keep me in the root directory, as sitemaps can \n')
        f.write('\tonly have access to urls contained within their directory.\n')
        f.write('\n')
        f.write('Example urlset:\n')
        f.write('\n')
        f.write('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
        f.write('\n')
        f.write('\t<url>\n')
        f.write('\n')
        f.write('\t\tIn practice, each of these pages should have the full url as the location\n')
        f.write('\t\t<loc>http://www.test.com/aboutus.html</loc>\n')
        f.write('\n')
        f.write('\t\tYYYY/MM/DD\n')
        f.write('\t\t<lastmod>2000-01-26</lastmod>\n')
        f.write('\n')
        f.write('\t\talways, hourly, daily, weekly, monthly, yearly, never\n')
        f.write('\t\t<changefreq>never</changefreq>\n')
        f.write('\n')
        f.write('\t\tUsed by search engines to rank most important page on the same site\n')
        f.write('\t\tDefault value is 0.5\n')
        f.write('\t\t<priority>0.1</priority>\n')
        f.write('\n')
        f.write('\t</url>\n')
        f.write('\n')
        f.write('\t<url>\n')
        f.write('\n')
        f.write('\t\t<loc>http://www.test.com/live.asp</loc>\n')
        f.write('\n')
        f.write('\t\t<lastmod>2019-09-5</lastmod>\n')
        f.write('\n')
        f.write('\t\t<changefreq>always</changefreq>\n')
        f.write('\n')
        f.write('\t\t<priority>0.9</priority>\n')
        f.write('\n')
        f.write('\t</url>\n')
        f.write('\n')
        f.write('</urlset>\n')
        f.write('-->\n')
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write('\n')
        f.write('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
        f.write('\t<url>\n')
        f.write('\t\t<loc>./index.html</loc>n\n')
        f.write('\t\t<lastmod>2019-09-5</lastmod>\n')
        f.write('\t</url>\n')
        f.write('</urlset>\n')
    with open(folder_name + 'robots.txt', 'w') as f:
        f.write('# Keep me in the root directory, as this is where bots will look for me.\n')
        f.write('\n')
        f.write('# Disallow all bots, except the ones specified below, from crawling the site\n')
        f.write('User-agent: *\n')
        f.write('Disallow: /\n')
        f.write('\n')
        f.write('User-agent: Googlebot\n')
        f.write('Allow: /\n')
        f.write('\n')
        f.write('Sitemap: ./sitemap.xml\n')
    open(folder_name + 'main.js', 'w')
    open(folder_name + 'badge.xml', 'w')
    open(folder_name + '1.xml', 'w')
    open(folder_name + '2.xml', 'w')
    with open(folder_name + 'Files_Needed.txt', 'w') as f:
        f.write('favicon.ico\n')
        f.write('favicon.svg\n')
        f.write('apple-touch-icon.png\n')
    with open(folder_name + 'media/Files_Needed.txt', 'w') as f:
        f.write('icons-192.png\n')
        f.write('icons-512.png\n')
        f.write('mstile-70x70.png\n')
        f.write('mstile-144x144.png\n')
        f.write('mstile-150x150.png\n')
        f.write('mstile-310x150.png\n')
        f.write('mstile-310x310.png\n')

new_project()
